---
baseurl: /knife-zero

# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Knife-Zero
tagline:          'Local Mode via SSH.'
description:      'Run chef-client at remote node with chef-zero(local-mode) via HTTP over SSH port fowarding. '
url:              http://higanworks.com

gems:
  - jekyll-sitemap

author:
  name:           'SAWANOBORI Yukihiko'
  url:            https://github.com/sawanoboly

paginate:         5

# Custom vars
version:          1.7.x

github:
  repo:  https://github.com/higanworks/knife-zero

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - vendor

